### ISSUE TITLE
miss the file of  balance sample 

### ISSUE THREAD

**Issue by JeffC0628** [YuanGongND/whisper-at#13]
Hi, Yuan

I'm training with full AS, and encountered some issues. I have attached my training log for reference.

1. I couldn't find the _*_weight.csv_ mentioned in _line 94_ of https://github.com/YuanGongND/whisper-at/blob/main/src/whisper_at_train/run.py.  https://github.com/YuanGongND/whisper-at/blob/82ccbf05d672ea60b9af76e35ce6abd705eda9cd/src/whisper_at_train/run.py#L94 Could you please provide it to help me reproduce the results?

2. The growth curve of the mAP in my train log differs significantly from the one you provided. My first epoch shows 0.017 mAP, while yours is 0.26. Does this indicate an error?
[my_large-v2_ori.txt](https://github.com/YuanGongND/whisper-at/files/13682109/my_large-v2_ori.txt)

3. I would like to know approximately how many GPUs and how much time it would take to run a single experiment.

**Comment by YuanGongND** [comment]
hi there,

> I couldn't find the _*weight.csv mentioned in line 94 of https://github.com/YuanGongND/whisper-at/blob/main/src/whisper_at_train/run.py.

Yes we intentionally not providing this as Audio set is not stable dataset, you need to calculate weight based on your own collection. See cd ast/egs/audioset
python gen_weight_file.py ./data/datafiles/train_data.json.

Please get the `gen_weight_file.py` in the corresponding repo. 

> The growth curve of the mAP in my train log differs significantly from the one you provided. My first epoch shows 0.017 mAP, while yours is 0.26. Does this indicate an error?

This is certainly abnormal, you should get very similar result with us (the different data collection will lead to slightly different results, but won't be very large). How did you deal with the missing weight file issue? If you did nothing, then that could be the problem. 

I suggest to keep everything unchanged, just to run our recipe, if successful then make the change.

> I would like to know approximately how many GPUs and how much time it would take to run a single experiment.

Check our log at https://github.com/YuanGongND/whisper-at/tree/main/src/whisper_at_train/log, the time is at the end of each epoch, also has breakdown for i/o and DNN training. For this project, i/o is the bottleneck. We used a5000 to train, but that might not be necessary. 

-Yuan

**Comment by JeffC0628** [comment]
> How did you deal with the missing weight file issue? If you did nothing, then that could be the problem.

I did nothing as I found there are two options: you can provide the weight file and the other is not the balanced sampling. I chose the second one. 

https://github.com/YuanGongND/whisper-at/blob/0bbb09f758ca5a411a43c34a02be7a6d648a2ebc/src/whisper_at_train/run.py#L103

I will generate my _*weight.csv_ file based on my training file, hope it's work.
appreciate it.

**Comment by YuanGongND** [comment]
Please let me know if it works.

**Comment by JeffC0628** [comment]
hi, yuan,
Sorry it took some time to run the experiment with 30-epoch, the result seems good, and the _weight.csv_ is crucial.
```

2023-12-21 05:00:55.723183
current #epochs=30, #steps=10962
Epoch: [30][38/3765]    Per Sample Total Time 0.06954   Per Sample Data Time 0.06520    Per Sample DNN Time 0.00434     |       Train Loss 0.0132
Epoch: [30][138/3765]   Per Sample Total Time 0.06808   Per Sample Data Time 0.06378    Per Sample DNN Time 0.00430     |       Train Loss 0.0129
Epoch: [30][238/3765]   Per Sample Total Time 0.06504   Per Sample Data Time 0.06074    Per Sample DNN Time 0.00430     |       Train Loss 0.0133
Epoch: [30][338/3765]   Per Sample Total Time 0.06489   Per Sample Data Time 0.06059    Per Sample DNN Time 0.00430     |       Train Loss 0.0136
start validation
mAP: 0.397363
AUC: 0.969771
d_prime: 2.655102
train_loss: 0.013086
valid_loss: 0.013435
validation finished
Epoch-30 lr: 1.58203125e-05
epoch 30 training time: 13312.540
wa 15 models from 16 to 30
<All keys matched successfully>

```

**Comment by YuanGongND** [comment]
hi Jeff,

thanks so much for reporting this. 

There should be a final line saying something like "mAP of model with weights averaged from checkpoint 16-30 is 0.4165", can you see that? That should be the final mAP. 

Also are you using large-v1 or large-v2? If you check the logs at https://github.com/YuanGongND/whisper-at/tree/main/src/whisper_at_train/log, you will notice that large-v1 would have a better result than large-v2. You result seems to be large-v2, is that true?

-Yuan

**Comment by JeffC0628** [comment]
Yuan,

> There should be a final line saying something like "mAP of model with weights averaged from checkpoint 16-30 is 0.4165", can you see that? That should be the final mAP.

1. sorry about losing the last line, 

```
---------------
2023-12-21 05:00:55.723183
current #epochs=30, #steps=10962
Epoch: [30][38/3765]    Per Sample Total Time 0.06954   Per Sample Data Time 0.06520    Per Sample DNN Time 0.00434     |       Train Loss 0.0132
Epoch: [30][138/3765]   Per Sample Total Time 0.06808   Per Sample Data Time 0.06378    Per Sample DNN Time 0.00430     |       Train Loss 0.0129
Epoch: [30][238/3765]   Per Sample Total Time 0.06504   Per Sample Data Time 0.06074    Per Sample DNN Time 0.00430     |       Train Loss 0.0133
Epoch: [30][338/3765]   Per Sample Total Time 0.06489   Per Sample Data Time 0.06059    Per Sample DNN Time 0.00430     |       Train Loss 0.0136
start validation
mAP: 0.397363
AUC: 0.969771
d_prime: 2.655102
train_loss: 0.013086
valid_loss: 0.013435
validation finished
Epoch-30 lr: 1.58203125e-05
epoch 30 training time: 13312.540
wa 15 models from 16 to 30
<All keys matched successfully>
mAP of model with weights averaged from checkpoint 16-30 is 0.4022

```



> Also are you using large-v1 or large-v2? If you check the logs at https://github.com/YuanGongND/whisper-at/tree/main/src/whisper_at_train/log, you will notice that large-v1 would have a better result than large-v2. You result seems to be large-v2, is that true?

2. I'm sure I use the large-v2, and I want to know how the large-v3 performs, can u predict it? :-)

**Comment by YuanGongND** [comment]
thanks so much. I were just trying to see how large is the difference between your result and ours. It seems there is still a 0.01 mAP difference on large-v2. See 

https://github.com/YuanGongND/whisper-at/blob/0bbb09f758ca5a411a43c34a02be7a6d648a2ebc/src/whisper_at_train/log/large-v2_ori.txt#L1666C61-L1666C67

It is not super large, but still a noticeable difference. 

Regarding v3, I don't know how it is trained, so it is hard for me to comment on that.

-Yuan

**Comment by YuanGongND** [comment]
it seems you are using a (much) larger batch size, which could be the reason for the difference.

**Comment by JeffC0628** [comment]
On the one hand, the batch size we use is different, and on the other hand, the audioset we use is different. There are only 1927774 samples in my audioset dataset, which is 25k less than your 1953082 samples. This is also one of the reasons for the difference in my opinion.
By the way, where can I download your 1953082-samples audioset? Do you provide a way to download it?

**Comment by YuanGongND** [comment]
25k data won't make a big difference, unless it has a special distribution (i.e., missing many samples for a minority class). Batch size could cause 0.01 mAP difference. If you aim to match exactly, you can try our batch size.

Due to copyright reasons, we cannot provide our data. But please check this https://github.com/YuanGongND/ast/issues/85. 

-Yuan
