### ISSUE TITLE
Still requests from url when models have been downloaded manually.

### ISSUE THREAD

**Issue by ndz2011** [YuanGongND/whisper-at#20]
It seems that  `__init__.py` requests from urls even when the model is manually downloaded, raising connection errors when urls are not accessible.

**Comment by YuanGongND** [comment]
hi there,

You probably can comment out the download line. The code has only been tested in automatic downloading situation.

-Yuan

**Comment by ndz2011** [comment]
> hi there,
> 
> You probably can comment out the download line. The code has only been tested in automatic downloading situation.
> 
> -Yuan

Thanks. It's solved.
