### ISSUE TITLE
downloading forms a bad path

### ISSUE THREAD

**Issue by raresv** [YuanGongND/whisper-at#3]
In some conditions, the URL passed to _download (in __init__.py) has the dl=1 GET parameter added which makes the download_target filename to be erroneously set as containing also that (eg: it ends up like "..... .cache\whisper\large-v2_ori.pth?dl=1")
A fix could be to:
from urllib.parse import urlparse
parsed_url = urlparse(url)
And then use parsed_url.path further.. such as instead of:
download_target = os.path.join(root, os.path.basename(url))
use
download_target = os.path.join(root, os.path.basename(parsed_url.path))

**Comment by YuanGongND** [comment]
hi there, 

Thanks for reporting this and proposing a solution. 

> In some conditions, the URL passed to _download (in init.py) has the dl=1 GET parameter added which makes the download_target filename to be erroneously set as containing also that (eg: it ends up like "..... .cache\whisper\large-v2_ori.pth?dl=1")

This is as expected, `dl=1` for dropbox means direct download without going to its page. The download file will have dl=1 in its name. But I am wondering if that would cause a practical problem, e.g., the downloaded file is cannot found by the script?

https://github.com/YuanGongND/whisper-at/blob/58fa38b1a998445c66db9f1bf2541d6665c7239c/package/whisper-at/whisper_at/__init__.py#L190

I set a strict check when loading the model, so it should report an error if the model file isn't found.

-Yuan

**Comment by raresv** [comment]
It triggers an error indeed, not at the model load phase but when trying to validate the download_target path. On Windows, so that's why the ? character creates a problem.
I fixed it locally by the method described above, otherwise it wouldn't work for me. I didn't create a pull request, but could do that if it helps.

**Comment by YuanGongND** [comment]
oh, I see. Thanks! I only tested on Ubuntu/mac. 

Will fix the problem follow your proposal, and go through a quick test. 

-Yuan

**Comment by YuanGongND** [comment]
Fixed in `whisper-at==0.4.0`. Thanks again for reporting this.

**Comment by raresv** [comment]
Thank you for all the great work you did here. Who knows, maybe we can contribute or extend this sometime.
